version: "3"
services:
  grafana:
    image: grafana/grafana-enterprise:7.5.13
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-lightstep-datasource,grafana-lightstep-graph,lightstep-app
      - GF_LOG_LEVEL=debug
      - GF_DEFAULT_APP_MODE=development
    volumes:
      - grafana-data-lgp:/var/lib/grafana
      - ./dist:/var/lib/grafana/plugins/lightstep-app

volumes:
  grafana-data-lgp:
    external: true